# Generated by Django 6.1 on 2026-08-17 19:27

import base.validators
import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('name', models.CharField(max_length=60, verbose_name='nome')),
                ('slug', models.SlugField(max_length=60, unique=True, verbose_name='identificador')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='preço')),
                ('is_enabled', models.BooleanField(default=False, help_text='Somente planos habilitados podem ser escolhidos no cadastro.', verbose_name='habilitado')),
                ('max_users', models.PositiveIntegerField(default=3, verbose_name='limite de usuários')),
                ('description', models.TextField(blank=True, verbose_name='descrição')),
            ],
            options={
                'verbose_name': 'plano',
                'verbose_name_plural': 'planos',
                'ordering': ['price', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('legal_name', models.CharField(max_length=200, verbose_name='razão social')),
                ('trade_name', models.CharField(blank=True, max_length=200, verbose_name='nome fantasia')),
                ('cnpj', models.CharField(max_length=18, unique=True, validators=[base.validators.validate_cnpj], verbose_name='CNPJ')),
                ('slug', models.SlugField(blank=True, max_length=80, unique=True, verbose_name='identificador')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='telefone')),
                ('susep_code', models.CharField(blank=True, max_length=30, verbose_name='código SUSEP')),
                ('logo', models.ImageField(blank=True, upload_to=core.models.tenant_logo_upload_to, verbose_name='logotipo')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativa')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tenants', to='core.plan', verbose_name='plano')),
            ],
            options={
                'verbose_name': 'corretora',
                'verbose_name_plural': 'corretoras',
                'ordering': ['legal_name'],
                'indexes': [models.Index(fields=['is_active'], name='tenant_is_active_idx')],
            },
        ),
    ]
